server:
  port: 565
spring:
  profiles:
      active: @profileActive@
  datasource:
        username: root
        password: 1ZatU6kDoB?8
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.47.26:3306/apollo?useUnicode=true&characterEncoding=utf-8
        type: com.alibaba.druid.pool.DruidDataSource
        dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
apollo:
  bootstrap:
    enabled: true
    namespaces: application,TEST1.apollo,application.yaml

